language: node_js
node_js:
    - "stable"
script:
  - npm run test
before_deploy:
  npm run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: $S3_BUCKET
  skip_cleanup: true
  local_dir: dist
  on:
    branch: master
